name: imboy
description: A new Flutter project for IM.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  # getx 状态管理框架
  get: ^4.3.4
  #演示列表需要用到的库
  dio: ^4.0.0    #网络请求框架
  json_annotation: ^4.0.1 #json序列化和反序列化用的
  #微信图库
  wechat_assets_picker: ^6.1.2
  # 对称加密
  encrypt: ^5.0.0
  # 非对称加密
  crypto: ^3.0.1
  uuid: ^3.0.4
  web_socket_channel: ^2.1.0
  # jwt 插件
  jose: ^0.3.2

  # 缓存
  shared_preferences: ^2.0.8
  cached_network_image: ^3.1.0
  flutter_cache_manager: ^3.1.3

  logger: ^1.0.0
  # sentry: ^6.0.1
  photo_view: ^0.13.0
  extended_text: ^7.0.0
  extended_text_field: ^8.0.0
  lpinyin: ^2.0.3
  azlistview: ^2.0.0-nullsafety.0
  video_player: ^2.2.5
  flutter_sound: ^8.3.12
  webview_flutter: ^2.1.1
  image_picker: ^0.8.4+2
  #extended_image: ^5.1.3
  #flutter_image_compress: ^1.1.0
  flutter_chat_ui: ^1.5.1
  mime: ^1.0.1
  file_picker: ^4.1.4
  open_file: ^3.2.1
  sqflite: ^2.0.0+4
  # 是否联网及网络类型
  connectivity_plus: ^2.0.2
  flutter_screenutil: ^5.0.0+2
  pull_to_refresh: ^2.0.0
  package_info_plus: ^1.3.0
  device_info_plus: ^3.1.0
  event_bus: ^2.0.0
  # https://github.com/letsar/flutter_slidable
  flutter_slidable: ^1.0.0
  # 消息提醒的红点效果
  badges: ^2.0.1
  # 聊天气泡
  bubble: ^1.2.1
  # getsocket: ^1.0.1

dev_dependencies:
  build_runner: ^2.1.4
  floor_generator: ^1.2.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  assets:
    - assets/data/messages.json
    - assets/images/def_avatar.png
    - assets/images/bsc.webp
    - assets/images/logo.png

    - assets/images/bar_close.png
    - assets/images/tabbar_contacts_c.webp
    - assets/images/tabbar_contacts_s.webp
    - assets/images/tabbar_discover_c.webp
    - assets/images/tabbar_discover_s.webp
    - assets/images/tabbar_chat_c.webp
    - assets/images/tabbar_chat_s.webp
    - assets/images/tabbar_me_c.webp
    - assets/images/tabbar_me_s.webp
    - assets/images/def_avatar.png
    - assets/images/search_black.webp
    - assets/images/search_white.png
    - assets/images/Contact_Female.webp
    - assets/images/Contact_Male.webp
    - assets/images/right_more.png
    - assets/images/favorite.webp
    - assets/images/contacts_add_newmessage.png
    - assets/images/add_addressicon.png
    - assets/images/ic_delete.webp
    - assets/images/ic_right_arrow_black.webp
    - assets/images/ic_right_arrow_grey.webp
    - assets/images/ic_add_friend.webp
    - assets/images/ic_no_data.webp

    - assets/images/chat/ic_Emotion.webp
    - assets/images/chat/ic_Keyboard.webp
    - assets/images/chat/ic_details_add.png
    - assets/images/chat/ic_voice.webp
    - assets/images/chat/ic_chat_more.webp
    - assets/images/chat/ic_chat_voice.webp
    - assets/images/chat/ic_details_camera.webp
    - assets/images/chat/ic_details_card.webp
    - assets/images/chat/ic_details_favorite.webp
    - assets/images/chat/ic_details_file.webp
    - assets/images/chat/ic_details_localtion.webp
    - assets/images/chat/ic_details_media.webp
    - assets/images/chat/ic_details_photo.webp
    - assets/images/chat/ic_details_red.webp
    - assets/images/chat/ic_details_transfer.webp
    - assets/images/chat/ic_details_video.webp
    - assets/images/chat/voice_volume_1.webp
    - assets/images/chat/voice_volume_2.webp
    - assets/images/chat/voice_volume_3.webp
    - assets/images/chat/voice_volume_4.webp
    - assets/images/chat/voice_volume_5.webp
    - assets/images/chat/voice_volume_6.webp
    - assets/images/chat/voice_volume_7.webp
    - assets/images/chat/sound_left_0.webp
    - assets/images/chat/sound_left_1.webp
    - assets/images/chat/sound_left_2.webp
    - assets/images/chat/sound_left_3.webp
    - assets/images/chat/sound_right_0.png
    - assets/images/chat/sound_right_1.webp
    - assets/images/chat/sound_right_2.webp
    - assets/images/chat/sound_right_3.png
    - assets/images/chat/icon_sight_close.png
    - assets/images/chat/flip_camera_icon_nor.webp

    - assets/images/mine/ic_small_code.png
    - assets/images/mine/ic_wallet.webp
    - assets/images/mine/ic_card_package.png
    - assets/images/mine/ic_emoji.png
    - assets/images/mine/ic_pay.png
    - assets/images/mine/ic_setting.png
    - assets/images/mine/ic_collections.png
    - assets/images/mine/ic_album.png
    - assets/images/mine/ic_social_circle.png

    - assets/images/contact/ic_contacts_details.png
    - assets/images/contact/ic_no_public.webp
    - assets/images/contact/ic_tag.webp
    - assets/images/contact/ic_group.webp
    - assets/images/contact/ic_new_friend.webp
    - assets/images/contact/ic_video.png
    - assets/images/contact/ic_voice.png
    - assets/images/contact/ic_offical.webp
    - assets/images/contact/ic_reda.webp
    - assets/images/contact/ic_scanqr.webp
    - assets/images/contact/ic_search_wework.webp
    - assets/images/contact/ic_contact_add.webp

    - assets/images/discover/ff_Icon_album.webp
    - assets/images/discover/ff_Icon_shake.webp
    - assets/images/discover/ff_Icon_bottle.webp
    - assets/images/discover/ff_Icon_browse.webp
    - assets/images/discover/ff_Icon_nearby.webp
    - assets/images/discover/ff_Icon_qr_code.webp
    - assets/images/discover/ff_Icon_search.webp
    - assets/images/discover/game_center_h5.webp
    - assets/images/discover/mini_program.webp
    - assets/images/emoji/
    - assets/images/group/
